Remove redundant logic in `invoke()`
eBay/imhotep pull request #1
Opened 2022-04-16 18:22 UTC by tslmy

Also clarified things quite a bit.

2022-04-16 23:31 UTC, justinabrahms requested changes

2022-04-16 23:31 UTC, justinabrahms commented on imhotep/app.py
> -                        x,
I believe this is a backwards incompatible change w/ the other reporters, no?

2022-04-17 00:30 UTC, tslmy commented
Are there other reporters?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Justin Abrahms ***@***.***>
Sent: Saturday, April 16, 2022 4:31:29 PM
To: eBay/imhotep ***@***.***>
Cc: Ming ***@***.***>; Author ***@***.***>
Subject: Re: [eBay/imhotep] Remove redundant logic in `invoke()` (PR #1)


@justinabrahms requested changes on this pull request.

________________________________

In imhotep/app.py<https://github.com/eBay/imhotep/pull/1#discussion_r851681807>:

>                  for i in matching_numbers:
                     error_count += 1
                     if error_count > max_errors:
                         continue
                     reporter.report_line(
                         cinfo.origin,
                         entry.result_filename,
-                        x,


I believe this is a backwards incompatible change w/ the other reporters, no?

—
Reply to this email directly, view it on GitHub<https://github.com/eBay/imhotep/pull/1#pullrequestreview-943893392>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAERBCXRM6YVSWHG64RW2I3VFNEVDANCNFSM5TSWJQUA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-17 00:33 UTC, justinabrahms commented
Thought so, but I don't see them. Maybe I never released them. Will give this another review pass this evening.

2022-04-17 00:35 UTC, tslmy commented
Cool. Just let me know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Justin Abrahms ***@***.***>
Sent: Saturday, April 16, 2022 5:33:45 PM
To: eBay/imhotep ***@***.***>
Cc: Ming ***@***.***>; Author ***@***.***>
Subject: Re: [eBay/imhotep] Remove redundant logic in `invoke()` (PR #1)


Thought so, but I don't see them. Maybe I never released them. Will give this another review pass this evening.

—
Reply to this email directly, view it on GitHub<https://github.com/eBay/imhotep/pull/1#issuecomment-1100777611>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAERBCWVGCMT33AU4M3ZFSDVFNL6TANCNFSM5TSWJQUA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-17 03:39 UTC, justinabrahms approved these changes

2022-04-17 03:39 UTC, merged